### ISSUE TITLE
Invalid zip?

### ISSUE THREAD

**Issue by redonkulousemu** [soburi/JN516x-arduino-package#4]
So I'm trying to install this on the arduino IDE, put in the link on board manager url, selected my board in tools, but when I try to compile, I get this error.

Arduino: 1.6.9 (Windows 7), Board: "NXP JN516x, JN5169"

Preparing package ...
Download https://github.com/soburi/contiki/archive/a61d7b9f7dc477e7df130842a5286f569a05c4bb.zip ...
Download complete.
Extract to ...
%!(EXTRA string=C:\Users\Emu\AppData\Local\Arduino15\packages\intiki\hardware\contiki\0.0.20160519\system\contiki)2016/06/22 15:22:04 zip: not a valid zip file
exit status 1
Error compiling for board NXP JN516x.

Maybe it is a IDE version issue and it's looking for a file in the zip that is not there?

**Comment by soburi** [comment]
I confirmed the problem has been reproduce.
It maybe mistake at the time of release.
Internally, the program downloading some zip files on first compile.
The url (in json) is maybe invalid.

Correct now.

**Comment by soburi** [comment]
I repaired the referenced repository (https://github.com/soburi/contiki) that was broken.

@redonkulousemu: It maybe fixed, Please retry to build.

In the long term, I need to setup automatically build system.

**Comment by soburi** [comment]
Complete setting up the automated release job.
