### ISSUE TITLE
tcp client can't connect to tcp server

### ISSUE THREAD

**Issue by dondipietro** [soburi/JN516x-arduino-package#61]
Dear Soburi,

I tested your examples on three JN5168 board, each with a different sketch : 
They are all running on the same time.

- tcp-echo-server-rpl give in terminal : 
"""
Contiki-1.6.9 started with IPV6, RPL
Node id is set to 45088.
nullsec CSMA nullrdc
Start Echo Server.
Start RPL with prefix AAAA::
""""

- tcpv6-client-example  give in terminal  : 
"""
Contiki-1.6.9 started with IPV6, RPL
Node id is set to 56915.
nullsec CSMA nullrdc
MicroIP.begin
connecting...

connection failed.
"""

-tcp-echo-client 
"""
Contiki-1.6.9 started with IPV6, RPL
Node id is set to 42437.
nullsec CSMA nullrdc
Start Echo Client.
connect 0
connect 0
connect 0
connect 0
""""

Is your arduino for jn516x able to use the wireless connection of the JN516x ?

Thank you for your help and your good work already done :D

![capture](https://user-images.githubusercontent.com/2470815/39948150-f19ac66c-5574-11e8-95d1-8f524f080440.PNG)

**Comment by dondipietro** [comment]
Thank you 👍

**Comment by dondipietro** [comment]
Hello, 
Your Udp7EchoClientServer is working good ;D ;D Thank you, it seem that TRACE must be off.

**Comment by soburi** [comment]
Sound good!
And Thank you for trying new example.
tcp client programs also checks will soon :-)
